function G=ErdosRenyi(n,p)
% ER is generated by choosing n the number of nodes and and p the probability of having an edge.
A = rand(n,n) < p; A = triu(A,1); A = A + A';
G = graph(A);

% % n = 20; p = 0.2;  %thres_giant = 1/(n-1)
% % A = rand(n,n) < p; A = triu(A,1); A = A + A';
% % G1 = graph(A); L0_1=laplacian(G1);
% % B = rand(n,n) < p; B = triu(B,1); B = B + B';
% % G2 = graph(B); L0_2=laplacian(G2);
